name: Deploy ECAST
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy to VPS
    runs-on: [self-hosted, club emis]
    env:
      NEXT_PUBLIC_BACKEND_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_URL }}
      NEXT_PUBLIC_CURRENT_BATCH_YEAR: ${{ secrets.NEXT_PUBLIC_CURRENT_BATCH_YEAR }}
      NEXT_PUBLIC_UMAMI_WEBSITE_ID: ${{ secrets.NEXT_PUBLIC_UMAMI_WEBSITE_ID }}
      UMAMI_BASE_URL: ${{ secrets.UMAMI_BASE_URL }}
      UMAMI_API_TOKEN: ${{ secrets.UMAMI_API_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Unified VPS Deployer
        run: |
          cd /srv/deployer
          node deploy.js $GITHUB_REPOSITORY
